// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Monitor.proto
#ifndef GRPC_Monitor_2eproto__INCLUDED
#define GRPC_Monitor_2eproto__INCLUDED

#include "Monitor.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace pb {

class Monitor final {
 public:
  static constexpr char const* service_full_name() {
    return "pb.Monitor";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetMonitor(::grpc::ClientContext* context, const ::pb::Request& request, ::pb::Reponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pb::Reponse>> AsyncGetMonitor(::grpc::ClientContext* context, const ::pb::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pb::Reponse>>(AsyncGetMonitorRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pb::Reponse>> PrepareAsyncGetMonitor(::grpc::ClientContext* context, const ::pb::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pb::Reponse>>(PrepareAsyncGetMonitorRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetMonitor(::grpc::ClientContext* context, const ::pb::Request* request, ::pb::Reponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetMonitor(::grpc::ClientContext* context, const ::pb::Request* request, ::pb::Reponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pb::Reponse>* AsyncGetMonitorRaw(::grpc::ClientContext* context, const ::pb::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pb::Reponse>* PrepareAsyncGetMonitorRaw(::grpc::ClientContext* context, const ::pb::Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetMonitor(::grpc::ClientContext* context, const ::pb::Request& request, ::pb::Reponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pb::Reponse>> AsyncGetMonitor(::grpc::ClientContext* context, const ::pb::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pb::Reponse>>(AsyncGetMonitorRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pb::Reponse>> PrepareAsyncGetMonitor(::grpc::ClientContext* context, const ::pb::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pb::Reponse>>(PrepareAsyncGetMonitorRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetMonitor(::grpc::ClientContext* context, const ::pb::Request* request, ::pb::Reponse* response, std::function<void(::grpc::Status)>) override;
      void GetMonitor(::grpc::ClientContext* context, const ::pb::Request* request, ::pb::Reponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::pb::Reponse>* AsyncGetMonitorRaw(::grpc::ClientContext* context, const ::pb::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pb::Reponse>* PrepareAsyncGetMonitorRaw(::grpc::ClientContext* context, const ::pb::Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetMonitor_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetMonitor(::grpc::ServerContext* context, const ::pb::Request* request, ::pb::Reponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetMonitor : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetMonitor() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetMonitor() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMonitor(::grpc::ServerContext* /*context*/, const ::pb::Request* /*request*/, ::pb::Reponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetMonitor(::grpc::ServerContext* context, ::pb::Request* request, ::grpc::ServerAsyncResponseWriter< ::pb::Reponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetMonitor<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetMonitor : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetMonitor() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::pb::Request, ::pb::Reponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::pb::Request* request, ::pb::Reponse* response) { return this->GetMonitor(context, request, response); }));}
    void SetMessageAllocatorFor_GetMonitor(
        ::grpc::MessageAllocator< ::pb::Request, ::pb::Reponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::pb::Request, ::pb::Reponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetMonitor() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMonitor(::grpc::ServerContext* /*context*/, const ::pb::Request* /*request*/, ::pb::Reponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetMonitor(
      ::grpc::CallbackServerContext* /*context*/, const ::pb::Request* /*request*/, ::pb::Reponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetMonitor<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetMonitor : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetMonitor() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetMonitor() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMonitor(::grpc::ServerContext* /*context*/, const ::pb::Request* /*request*/, ::pb::Reponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetMonitor : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetMonitor() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetMonitor() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMonitor(::grpc::ServerContext* /*context*/, const ::pb::Request* /*request*/, ::pb::Reponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetMonitor(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetMonitor : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetMonitor() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetMonitor(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetMonitor() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMonitor(::grpc::ServerContext* /*context*/, const ::pb::Request* /*request*/, ::pb::Reponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetMonitor(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetMonitor : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetMonitor() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::pb::Request, ::pb::Reponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::pb::Request, ::pb::Reponse>* streamer) {
                       return this->StreamedGetMonitor(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetMonitor() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetMonitor(::grpc::ServerContext* /*context*/, const ::pb::Request* /*request*/, ::pb::Reponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetMonitor(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::pb::Request,::pb::Reponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetMonitor<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetMonitor<Service > StreamedService;
};

}  // namespace pb


#endif  // GRPC_Monitor_2eproto__INCLUDED
