// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Monitor.proto

#include "Monitor.pb.h"
#include "Monitor.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace pb {

static const char* Monitor_method_names[] = {
  "/pb.Monitor/GetMonitor",
};

std::unique_ptr< Monitor::Stub> Monitor::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Monitor::Stub> stub(new Monitor::Stub(channel, options));
  return stub;
}

Monitor::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetMonitor_(Monitor_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Monitor::Stub::GetMonitor(::grpc::ClientContext* context, const ::pb::Request& request, ::pb::Reponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::pb::Request, ::pb::Reponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetMonitor_, context, request, response);
}

void Monitor::Stub::async::GetMonitor(::grpc::ClientContext* context, const ::pb::Request* request, ::pb::Reponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::pb::Request, ::pb::Reponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMonitor_, context, request, response, std::move(f));
}

void Monitor::Stub::async::GetMonitor(::grpc::ClientContext* context, const ::pb::Request* request, ::pb::Reponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMonitor_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::pb::Reponse>* Monitor::Stub::PrepareAsyncGetMonitorRaw(::grpc::ClientContext* context, const ::pb::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::pb::Reponse, ::pb::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetMonitor_, context, request);
}

::grpc::ClientAsyncResponseReader< ::pb::Reponse>* Monitor::Stub::AsyncGetMonitorRaw(::grpc::ClientContext* context, const ::pb::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetMonitorRaw(context, request, cq);
  result->StartCall();
  return result;
}

Monitor::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Monitor_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Monitor::Service, ::pb::Request, ::pb::Reponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Monitor::Service* service,
             ::grpc::ServerContext* ctx,
             const ::pb::Request* req,
             ::pb::Reponse* resp) {
               return service->GetMonitor(ctx, req, resp);
             }, this)));
}

Monitor::Service::~Service() {
}

::grpc::Status Monitor::Service::GetMonitor(::grpc::ServerContext* context, const ::pb::Request* request, ::pb::Reponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace pb

