// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Close():Promise<void>;

export function Collect(arg1:string,arg2:number):Promise<main.MonitorInfo>;

export function NewCollect(arg1:string,arg2:number):Promise<main.Collect>;
