// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['Collect']['Close']();
}

export function CreateConn(arg1, arg2) {
  return window['go']['main']['Collect']['CreateConn'](arg1, arg2);
}

export function Delete(arg1, arg2) {
  return window['go']['main']['Collect']['Delete'](arg1, arg2);
}

export function GetCpu(arg1, arg2) {
  return window['go']['main']['Collect']['GetCpu'](arg1, arg2);
}

export function GetMem(arg1, arg2) {
  return window['go']['main']['Collect']['GetMem'](arg1, arg2);
}

export function GetNets(arg1, arg2) {
  return window['go']['main']['Collect']['GetNets'](arg1, arg2);
}

export function GetProcs(arg1, arg2) {
  return window['go']['main']['Collect']['GetProcs'](arg1, arg2);
}
