// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['Collect']['Close']();
}

export function Collect(arg1, arg2) {
  return window['go']['main']['Collect']['Collect'](arg1, arg2);
}

export function NewCollect(arg1, arg2) {
  return window['go']['main']['Collect']['NewCollect'](arg1, arg2);
}
