// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.1
// source: protos/Monitor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_Monitor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_protos_Monitor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_protos_Monitor_proto_rawDescGZIP(), []int{0}
}

type Cpu struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CoreNum int64     `protobuf:"varint,2,opt,name=core_num,json=coreNum,proto3" json:"core_num,omitempty"`
	CpuHz   float32   `protobuf:"fixed32,3,opt,name=cpu_hz,json=cpuHz,proto3" json:"cpu_hz,omitempty"`
	CpuS    []float32 `protobuf:"fixed32,4,rep,packed,name=cpu_s,json=cpuS,proto3" json:"cpu_s,omitempty"`
}

func (x *Cpu) Reset() {
	*x = Cpu{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_Monitor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cpu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cpu) ProtoMessage() {}

func (x *Cpu) ProtoReflect() protoreflect.Message {
	mi := &file_protos_Monitor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cpu.ProtoReflect.Descriptor instead.
func (*Cpu) Descriptor() ([]byte, []int) {
	return file_protos_Monitor_proto_rawDescGZIP(), []int{1}
}

func (x *Cpu) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cpu) GetCoreNum() int64 {
	if x != nil {
		return x.CoreNum
	}
	return 0
}

func (x *Cpu) GetCpuHz() float32 {
	if x != nil {
		return x.CpuHz
	}
	return 0
}

func (x *Cpu) GetCpuS() []float32 {
	if x != nil {
		return x.CpuS
	}
	return nil
}

type Mem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total     int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Free      int64 `protobuf:"varint,2,opt,name=free,proto3" json:"free,omitempty"`
	Available int64 `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	Cached    int64 `protobuf:"varint,4,opt,name=cached,proto3" json:"cached,omitempty"`
	SwapTotal int64 `protobuf:"varint,5,opt,name=swap_total,json=swapTotal,proto3" json:"swap_total,omitempty"`
	SwapFree  int64 `protobuf:"varint,6,opt,name=swap_free,json=swapFree,proto3" json:"swap_free,omitempty"`
}

func (x *Mem) Reset() {
	*x = Mem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_Monitor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mem) ProtoMessage() {}

func (x *Mem) ProtoReflect() protoreflect.Message {
	mi := &file_protos_Monitor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mem.ProtoReflect.Descriptor instead.
func (*Mem) Descriptor() ([]byte, []int) {
	return file_protos_Monitor_proto_rawDescGZIP(), []int{2}
}

func (x *Mem) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Mem) GetFree() int64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *Mem) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *Mem) GetCached() int64 {
	if x != nil {
		return x.Cached
	}
	return 0
}

func (x *Mem) GetSwapTotal() int64 {
	if x != nil {
		return x.SwapTotal
	}
	return 0
}

func (x *Mem) GetSwapFree() int64 {
	if x != nil {
		return x.SwapFree
	}
	return 0
}

type Net struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Upload    int64  `protobuf:"varint,2,opt,name=upload,proto3" json:"upload,omitempty"`
	UploadS   int64  `protobuf:"varint,3,opt,name=upload_s,json=uploadS,proto3" json:"upload_s,omitempty"`
	Download  int64  `protobuf:"varint,4,opt,name=download,proto3" json:"download,omitempty"`
	DownloadS int64  `protobuf:"varint,5,opt,name=download_s,json=downloadS,proto3" json:"download_s,omitempty"`
}

func (x *Net) Reset() {
	*x = Net{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_Monitor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net) ProtoMessage() {}

func (x *Net) ProtoReflect() protoreflect.Message {
	mi := &file_protos_Monitor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net.ProtoReflect.Descriptor instead.
func (*Net) Descriptor() ([]byte, []int) {
	return file_protos_Monitor_proto_rawDescGZIP(), []int{3}
}

func (x *Net) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Net) GetUpload() int64 {
	if x != nil {
		return x.Upload
	}
	return 0
}

func (x *Net) GetUploadS() int64 {
	if x != nil {
		return x.UploadS
	}
	return 0
}

func (x *Net) GetDownload() int64 {
	if x != nil {
		return x.Download
	}
	return 0
}

func (x *Net) GetDownloadS() int64 {
	if x != nil {
		return x.DownloadS
	}
	return 0
}

type Proc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Usr       string  `protobuf:"bytes,2,opt,name=usr,proto3" json:"usr,omitempty"`
	State     string  `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Pid       int64   `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	Mem       int64   `protobuf:"varint,5,opt,name=mem,proto3" json:"mem,omitempty"`
	ThreadNum int64   `protobuf:"varint,6,opt,name=thread_num,json=threadNum,proto3" json:"thread_num,omitempty"`
	CpuS      float32 `protobuf:"fixed32,7,opt,name=cpu_s,json=cpuS,proto3" json:"cpu_s,omitempty"`
}

func (x *Proc) Reset() {
	*x = Proc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_Monitor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Proc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proc) ProtoMessage() {}

func (x *Proc) ProtoReflect() protoreflect.Message {
	mi := &file_protos_Monitor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proc.ProtoReflect.Descriptor instead.
func (*Proc) Descriptor() ([]byte, []int) {
	return file_protos_Monitor_proto_rawDescGZIP(), []int{4}
}

func (x *Proc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Proc) GetUsr() string {
	if x != nil {
		return x.Usr
	}
	return ""
}

func (x *Proc) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Proc) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Proc) GetMem() int64 {
	if x != nil {
		return x.Mem
	}
	return 0
}

func (x *Proc) GetThreadNum() int64 {
	if x != nil {
		return x.ThreadNum
	}
	return 0
}

func (x *Proc) GetCpuS() float32 {
	if x != nil {
		return x.CpuS
	}
	return 0
}

var File_protos_Monitor_proto protoreflect.FileDescriptor

var file_protos_Monitor_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x09, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x60, 0x0a, 0x03, 0x43, 0x70, 0x75, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x63, 0x6f, 0x72, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x15, 0x0a, 0x06, 0x63,
	0x70, 0x75, 0x5f, 0x68, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x63, 0x70, 0x75,
	0x48, 0x7a, 0x12, 0x13, 0x0a, 0x05, 0x63, 0x70, 0x75, 0x5f, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x02, 0x52, 0x04, 0x63, 0x70, 0x75, 0x53, 0x22, 0xa1, 0x01, 0x0a, 0x03, 0x4d, 0x65, 0x6d, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x65, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x72, 0x65, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x61, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x63, 0x68, 0x65,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x77, 0x61, 0x70, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x77, 0x61, 0x70, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1b,
	0x0a, 0x09, 0x73, 0x77, 0x61, 0x70, 0x5f, 0x66, 0x72, 0x65, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x73, 0x77, 0x61, 0x70, 0x46, 0x72, 0x65, 0x65, 0x22, 0x87, 0x01, 0x0a, 0x03,
	0x4e, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x6f,
	0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x6f,
	0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x5f, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x64, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x53, 0x22, 0x9a, 0x01, 0x0a, 0x04, 0x50, 0x72, 0x6f, 0x63, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x73, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x73, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x65, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6d, 0x65, 0x6d, 0x12, 0x1d,
	0x0a, 0x0a, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x4e, 0x75, 0x6d, 0x12, 0x13, 0x0a,
	0x05, 0x63, 0x70, 0x75, 0x5f, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x63, 0x70,
	0x75, 0x53, 0x32, 0x91, 0x01, 0x0a, 0x07, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x12, 0x1e,
	0x0a, 0x06, 0x47, 0x65, 0x74, 0x43, 0x70, 0x75, 0x12, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x70, 0x75, 0x12, 0x1e,
	0x0a, 0x06, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x12, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x6d, 0x12, 0x21,
	0x0a, 0x07, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x74, 0x73, 0x12, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x65, 0x74, 0x30,
	0x01, 0x12, 0x23, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x73, 0x12, 0x0b, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x08, 0x2e, 0x70, 0x62, 0x2e,
	0x50, 0x72, 0x6f, 0x63, 0x30, 0x01, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_Monitor_proto_rawDescOnce sync.Once
	file_protos_Monitor_proto_rawDescData = file_protos_Monitor_proto_rawDesc
)

func file_protos_Monitor_proto_rawDescGZIP() []byte {
	file_protos_Monitor_proto_rawDescOnce.Do(func() {
		file_protos_Monitor_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_Monitor_proto_rawDescData)
	})
	return file_protos_Monitor_proto_rawDescData
}

var file_protos_Monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protos_Monitor_proto_goTypes = []interface{}{
	(*Request)(nil), // 0: pb.Request
	(*Cpu)(nil),     // 1: pb.Cpu
	(*Mem)(nil),     // 2: pb.Mem
	(*Net)(nil),     // 3: pb.Net
	(*Proc)(nil),    // 4: pb.Proc
}
var file_protos_Monitor_proto_depIdxs = []int32{
	0, // 0: pb.Monitor.GetCpu:input_type -> pb.Request
	0, // 1: pb.Monitor.GetMem:input_type -> pb.Request
	0, // 2: pb.Monitor.GetNets:input_type -> pb.Request
	0, // 3: pb.Monitor.GetProcs:input_type -> pb.Request
	1, // 4: pb.Monitor.GetCpu:output_type -> pb.Cpu
	2, // 5: pb.Monitor.GetMem:output_type -> pb.Mem
	3, // 6: pb.Monitor.GetNets:output_type -> pb.Net
	4, // 7: pb.Monitor.GetProcs:output_type -> pb.Proc
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_Monitor_proto_init() }
func file_protos_Monitor_proto_init() {
	if File_protos_Monitor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_Monitor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_Monitor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cpu); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_Monitor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_Monitor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_Monitor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Proc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_Monitor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_Monitor_proto_goTypes,
		DependencyIndexes: file_protos_Monitor_proto_depIdxs,
		MessageInfos:      file_protos_Monitor_proto_msgTypes,
	}.Build()
	File_protos_Monitor_proto = out.File
	file_protos_Monitor_proto_rawDesc = nil
	file_protos_Monitor_proto_goTypes = nil
	file_protos_Monitor_proto_depIdxs = nil
}
